### ISSUE TITLE
Data Science tools Plankton refactor

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/nautilina#8]
The idea is to list the things to refactor in the Datascience tools project (sorted by priority):

- [ ]  [oceanprotocol/nautilina](oceanprotocol/nautilina)
   - [x] Example 1) 
      - [x] Test
   - [x] Example 2)
      - [x] Test
   - [x] Example 3)
      - [x] Test
   - [ ] Example 4)
      - [ ] Test
   - [ ] Example 5)
      - [ ] Add docstrings: [nautilina/toyexample5/backend/app.py](nautilina/toyexample5/backend/app.py)
      - [ ] Add Swagger UI: [nautilina/toyexample5/backend/app.py](nautilina/toyexample5/backend/app.py)

After reviewing this, each entry will be an independent user story to be implemented in the following days.

**Comment by aaitor** [comment]
Most of the ocean-web3 refactor is being implemented by @eruizgar91 , moving the common web3 business logic used in the provider in the common library. I would move those ocean-web3 tasks to the provider side, focusing here only in the pure data science tools.

**Comment by aaitor** [comment]
@MarcusJones , can you update the state of this please?

**Comment by MarcusJones** [comment]
This logic is superseded by [mantaray](/oceanprotocol/mantaray), closing.
